#!/bin/bash

docker run  \
  --env-file docker.env \
  --volume /home/robert/Documents/Docker/mirror-buckets/data:/media/destination:rw \
  --volume /home/robert/Documents/Docker/mirror-buckets/rclone.conf:/root/.config/rclone/rclone.conf:ro \
  --volume /home/robert/Documents/Docker/mirror-buckets/config.json:/home/app/config.json:ro \
  --rm \
  robertgauld/mirror-buckets
